application: slidefunder
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

# bootstrip url links
- url: /bootstrap/css
  mime_type: text/css
  static_dir: bootstrap/css

- url: /bootstrap/js
  mime_type: text/javascript
  static_dir: bootstrap/js

- url: /bootstrap/img/(.*\.(gif|png|jpg))
  static_files: bootstrap/img/\1
  upload: bootstrap/img/(.*\.(gif|png|jpg))


# urls for static stylesheets
- url: /stylesheets/css
  mime_type: text/css
  static_dir: stylesheets/css

- url: /stylesheets/js
  mime_type: text/javascript
  static_dir: stylesheets/js

- url: /stylesheets
  static_dir: stylesheets

- url: /bootstrap
  static_dir: bootstrap

- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest